### ISSUE TITLE
Add mixxx-9999 ebuild

### ISSUE THREAD

**Issue by Tratoschek** [gentoo-audio/audio-overlay#56] opened 2017-07-02 22:10 UTC
First, thank you for your work. I want to suggest to add a mixxx-9999.ebuild. The release versions of Mixxx are in the main Gentoo repo, but the last Mixxx release was a long time ago, although development is pretty active.

The proaudio overlay ebuild is kind of outdated, so I made my own based on the one from Gentoo (a few month ago). Nevertheless this needs to be updated and controlled (but compiles and works fine so far): [mixxx-9999.ebuild.txt](https://github.com/gentoo-audio/audio-overlay/files/1118133/mixxx-9999.ebuild.txt)
(Once, I have more time, I'll make a pull request.)

**Comment by simonvanderveldt** [comment] 2017-07-03 08:52
Thanks for the suggestion! Since mixxx is already in the gentoo tree would it be OK for you if we try to add it to the gentoo tree?

**Comment by Tratoschek** [comment] 2017-07-03 11:37
Of course, the attached ebuild is already written in such a way.

**Comment by tekhedd** [comment] 2017-09-23 06:44
I've been searching for two days to find an overlay of mixxx-git for gentoo. (technically, funtoo). Mixxx on gentoo with realtime priority is simply the best. But, Mixxx 2.0 is ancient in software terms (the ebuild has like 20 patches) and has some issues that keep it just one tiny tick short of prime time.

Have you considered setting up a github mixxx-git overlay repo for layman? I know, more work! :P But... it would definitely get people using 2.1.

I started to work on an ebuild, but I run a systemd-free build and the consolekit requirement stopped me cold (enough said about that--systemd has accomplished what I thought nothing else could do: made me prefer other platforms to linux). (Also, I'd be willing to put in the work to make consolekit optional if this is considered acceptable but this is so utterly OT.) The main point is: what's the best way to set up and maintain an overlay for general community use? I don't think within the mixxx project, I think as a parallel repo.

**Comment by Tratoschek** [comment] 2017-09-24 02:56
> I started to work on an ebuild, but I run a systemd-free build and the consolekit requirement stopped me cold.

What do you mean with consolekit requirement?

> The main point is: what's the best way to set up and maintain an overlay for general community use?

Just set up your [personal overlay](https://wiki.gentoo.org/wiki/Handbook:Parts/Portage/CustomTree#Defining_a_custom_repository) and put the mixxx ebuild in it. If you are fine with the ebuilds, put the overlay into a git repo and upload it to github.
Anyway, the way of getting it to the gentoo tree is imho the better way (and uploading a recent ebuild to the bugtracker).

**Comment by simonvanderveldt** [comment] 2017-09-25 09:06
I've created this bug to check/request a 9999 ebuild for mixxx, please comment there if you want a 9999 version as well.

@Tratoschek Can you post your ebuild in that bug? (or create a PR to https://github.com/gentoo/gentoo mentioning that bug)

Closing this issue since we want this fixed upstream

**Closed by simonvanderveldt** 2017-09-25 09:06 UTC

**Comment by Tratoschek** [comment] 2017-09-25 11:41
What bug?

**Comment by simonvanderveldt** [comment] 2017-09-25 12:16
@Tratoschek sorry, forgot to add the link. I've updated my comment.

**Comment by tekhedd** [comment] 2017-09-25 16:57
OK so manual overlay management with local ebuilds is the answer. 

The upstream response today is as expected: 

> mixxx-2.0.0 is requiring a huge amount of downstream patching by now. Could you ping upstream for their plan of a new release?

It's true, there are a LOT of patches applied to get 2.0 to build. They will be reluctant to add an official ebuild to Gentoo unless there is some sort of tagged release to point to, even if it's just a designated official nightly builds. Looking at the issue chart, it does look like Mixxx is overdue for a "bugfix only" release branch. 

Also, the root cause of this issue (the need for a dev ebuild) is the lack of an official release. So, maybe tagged "wontfix" I guess. ;)

> What do you mean with consolekit requirement?

Specifically, the "battery display" requires upower-glib, which uses consolekit, and therefore policykit. I was hoping to avoid installing it on my stripped dev/audio system, but Mixxx is cool enough that I might compromise my principles and just deal with it. I would really prefer to have the option, though. Definitely something for a separate ticket.

**Comment by simonvanderveldt** [comment] 2018-05-11 21:33
FYI there's now a mixxx [2.1.0](https://github.com/gentoo/gentoo/commit/6ff404a723a95fec30cbb336a8fb2e71aa3aed49#diff-6486a091e43379fc13028f00f6fa6473) and [live](https://github.com/gentoo/gentoo/commit/d4c8bfa924b8b2f70914eaf9eb34b90107275d6c#diff-e5ba46a1a331a359be5ae06d5263b47e) ebuild in the gentoo tree :)

**Comment by Tratoschek** [comment] 2018-05-12 11:52
Nice, thank you and Polynomial-C.
